[job]
dump_folder = "./outputs"
description = "Qwen 3 0.6B training"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 1
enable_tensorboard = false
enable_wandb = false
enable_aim = true
save_tb_folder = "tb"
save_for_all_ranks = false

[model]
name = "qwen3"
flavor = "0.6B"
hf_assets_path = "./assets/hf/Qwen3-0.6B"
#converters = ["float8"]
converters = ["quantize.linear.mx"]

[optimizer]
name = "AdamW"
lr = 3e-4
eps = 1e-8

[lr_scheduler]
warmup_steps = 2  # lr scheduler warm up, 20% total steps

[training]
global_batch_size = 16
local_batch_size = 2
seq_len = 4096
max_norm = 1.0  # grad norm clipping
steps = 20000
dataset = "c4"

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
fsdp_reshard_after_forward = "default" # default / never / always
tensor_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable = true
folder = "checkpoint"
interval = 500
last_save_model_only = false
export_dtype = "float16"
keep_latest_k = 2
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = "selective"  # ["none", "selective", "full"]
selective_ac_option = "op"  # "int" = ac every positive int layer or 'op', ac based on ops policy

[compile]
enable=true
components = ["model", "loss"]

[quantize.linear.mx]
recipe_name = "mxfp8_cublas"                    # Default recipe
mxfp8_dim1_cast_kernel_choice = "cuda"          # Options: "triton", "cuda", "torch" 
filter_fqns = ["output"]                        # Modules to skip (default skips output layer)
